spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/doca"
    username: "postgres"
    password: 1
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/start.sql
    user: "postgres"
    password: 1
    url: "jdbc:postgresql://localhost:5432/doca"
    clear-checksums: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret: "Super1Secret2Word3To4MyToken8And9HisSoStrong"
    expired: 28800000 #1000*60*60*8 8 часов
server:
  port: 7777