spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/doca"
    username: "postgres"
    password: 1
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/start.sql
    user: "postgres"
    password: 1
    url: "jdbc:postgresql://localhost:5432/doca"
    clear-checksums: true
jwt:
  token:
    secret: "Super1Secret2Word3To4MyToken8And9HisSoStrong"
    expired: 28800000 #1000*60*60*8 8 часов
server:
  port: 7777